### ISSUE TITLE
Module: twoslash does not support tsconfig.json "paths" which is an object

### ISSUE THREAD

**Issue by mmorearty** [microsoft/TypeScript-Website#1555]
I can't find any way to get twoslash to support the "paths" property of tsconfig.json. It seems like there is code that's intended to work with object; see [here](https://github.com/microsoft/TypeScript-Website/blob/2a0ad5736cde9181925c05e66825c87095472dbc/packages/ts-twoslasher/src/index.ts#L165-L169). However, when I put this in a twoslash document, I get an error:

```
// @paths: { "*": [ "*", "lib/*" ] }
```

E.g. if you try that on [bug workbench](https://www.typescriptlang.org/dev/bug-workbench/?#code/PTAEAEAcEMBcAsDOAuUBvUAiAVJ1BtLXAGiwBsBLAI2F1AF1QBfAWACgg), you get this:

```
TypeError: r.get is not a function
    at c (https://www.typescriptlang.org/17821066377c4486a980330106160c805ea5b4a9-3746668446b11083d639.js:1:1685)
    at i (https://www.typescriptlang.org/17821066377c4486a980330106160c805ea5b4a9-3746668446b11083d639.js:1:2360)
    at f (https://www.typescriptlang.org/17821066377c4486a980330106160c805ea5b4a9-3746668446b11083d639.js:1:2481)
    at https://www.typescriptlang.org/17821066377c4486a980330106160c805ea5b4a9-3746668446b11083d639.js:1:4204
    at g (https://www.typescriptlang.org/17821066377c4486a980330106160c805ea5b4a9-3746668446b11083d639.js:1:4244)
    at j (https://www.typescriptlang.org/component---src-pages-dev-bug-workbench-tsx-52a0293ef52c1fc9cf74.js:1:5437)
    at https://www.typescriptlang.org/component---src-pages-dev-bug-workbench-tsx-52a0293ef52c1fc9cf74.js:1:4882
    at n (https://www.typescriptlang.org/17821066377c4486a980330106160c805ea5b4a9-3746668446b11083d639.js:1:23019)

```

I tried every variation on the directive that I could think of. Looking at the code, I think it's probably a bug.

cc @d-fischer , who I think did some recent work on this code in [this commit](https://github.com/microsoft/TypeScript-Website/commit/02b5b3b4532a19749db28c791fe09e9d3d93e123)

**Comment by orta** [comment]
I'm not sure  @d-fischer's code would cover this, as it adds arrays `["es2015", "dom"]` not objects `{ "*": {... } }`

I've not needed this feature for the TS docs, so I've not added support - happy to take PRs on it 👍🏻
