### ISSUE TITLE
Module: tsvsf - FSBackedSystem has a fixed getCurrentDirectory() that breaks relative imports

### ISSUE THREAD

**Issue by kevinramharak** [microsoft/TypeScript-Website#1669]
Im using `@typescript/vfs` and its `createFSBackedSystem` to create an environment to test my transformer. I stumbled on the following problem where I am trying to figure out what the intention of the following line is:
https://github.com/microsoft/TypeScript-Website/blob/4700f41b706108a515c9f40dbcd17e453b7856e4/packages/typescript-vfs/src/index.ts#L432

This breaks relative imports when a file is read from disk but im not sure why. When I override `system.getCurrentDirectory` with `() => process.cwd()` everything works as expected, but I'm not sure why.

For example:
```ts
// test/values.ts

export const value = 42;
```
```ts
// test/objects/interfaces.ts:3:73

import { value } from '../values';
// AssertionError: test/objects/interfaces.ts:3:73 Cannot find module '../values' or its corresponding type declarations
```

I tried setting `host.resolveModulesNames` to see if the compiler would use that instead, but that doesnt seem to be used at all.
I dumped a stack trace to see why `system.getCurrentDirectory` is being used to resolve file relative imports but I'm a bit lost on why the compiler does it like this.

<details>
<summary>
It seems that <a href="https://github.com/microsoft/TypeScript/blob/master/src/compiler/utilities.ts#L4168)"><code>src/compiler/utilities.ts#getPathsBasePath</code></a> is being used to figure out from where relative paths should be resolved
</summary>

```
at Object.getCurrentDirectory (C:\Users\kevin\Documents\Projects\ts-transform-runtime-check\test\createEnvironment.ts:51:21)
    at Object.getPathsBasePath (C:\Users\kevin\Documents\Projects\ts-transform-runtime-check\node_modules\typescript\lib\typescript.js:17451:192)       
    at tryLoadModuleUsingPathsIfEligible (C:\Users\kevin\Documents\Projects\ts-transform-runtime-check\node_modules\typescript\lib\typescript.js:39662:36)
    at tryLoadModuleUsingOptionalResolutionSettings (C:\Users\kevin\Documents\Projects\ts-transform-runtime-check\node_modules\typescript\lib\typescript.js:39643:24)
    at tryResolve (C:\Users\kevin\Documents\Projects\ts-transform-runtime-check\node_modules\typescript\lib\typescript.js:39788:28)
    at C:\Users\kevin\Documents\Projects\ts-transform-runtime-check\node_modules\typescript\lib\typescript.js:39784:69
    at Object.forEach (C:\Users\kevin\Documents\Projects\ts-transform-runtime-check\node_modules\typescript\lib\typescript.js:384:30)
    at nodeModuleNameResolverWorker (C:\Users\kevin\Documents\Projects\ts-transform-runtime-check\node_modules\typescript\lib\typescript.js:39784:25)   
    at nodeModuleNameResolver (C:\Users\kevin\Documents\Projects\ts-transform-runtime-check\node_modules\typescript\lib\typescript.js:39776:16)
    at Object.resolveModuleName (C:\Users\kevin\Documents\Projects\ts-transform-runtime-check\node_modules\typescript\lib\typescript.js:39547:30)       
    at loader_1 (C:\Users\kevin\Documents\Projects\ts-transform-runtime-check\node_modules\typescript\lib\typescript.js:106565:99)
    at loadWithLocalCache (C:\Users\kevin\Documents\Projects\ts-transform-runtime-check\node_modules\typescript\lib\typescript.js:106314:42)
    at actualResolveModuleNamesWorker (C:\Users\kevin\Documents\Projects\ts-transform-runtime-check\node_modules\typescript\lib\typescript.js:106566:129)
    at resolveModuleNamesWorker (C:\Users\kevin\Documents\Projects\ts-transform-runtime-check\node_modules\typescript\lib\typescript.js:106803:26)      
    at resolveModuleNamesReusingOldState (C:\Users\kevin\Documents\Projects\ts-transform-runtime-check\node_modules\typescript\lib\typescript.js:106900:24)
    at processImportedModules (C:\Users\kevin\Documents\Projects\ts-transform-runtime-check\node_modules\typescript\lib\typescript.js:108351:35)        
    at findSourceFileWorker (C:\Users\kevin\Documents\Projects\ts-transform-runtime-check\node_modules\typescript\lib\typescript.js:108153:17)
    at findSourceFile (C:\Users\kevin\Documents\Projects\ts-transform-runtime-check\node_modules\typescript\lib\typescript.js:108014:26)
    at C:\Users\kevin\Documents\Projects\ts-transform-runtime-check\node_modules\typescript\lib\typescript.js:107966:85
    at getSourceFileFromReferenceWorker (C:\Users\kevin\Documents\Projects\ts-transform-runtime-check\node_modules\typescript\lib\typescript.js:107933:34)
    at processSourceFile (C:\Users\kevin\Documents\Projects\ts-transform-runtime-check\node_modules\typescript\lib\typescript.js:107966:13)
    at processRootFile (C:\Users\kevin\Documents\Projects\ts-transform-runtime-check\node_modules\typescript\lib\typescript.js:107776:13)
    at C:\Users\kevin\Documents\Projects\ts-transform-runtime-check\node_modules\typescript\lib\typescript.js:106658:67
    at Object.forEach (C:\Users\kevin\Documents\Projects\ts-transform-runtime-check\node_modules\typescript\lib\typescript.js:384:30)
    at Object.createProgram (C:\Users\kevin\Documents\Projects\ts-transform-runtime-check\node_modules\typescript\lib\typescript.js:106658:16)
```
</details>

Any ideas on what im missing here? I'd like `vfs` to behave as expected in its node environment, but im lost on what is going wrong here.

**Comment by orta** [comment]
I used the static root because I figured that was the project root and the cwd for the project. I'd be surprised if TypeScript was expecting the cwd to change depending on a relative file. I think it might be a good idea to add a test case for it in the vfs package

**Comment by kevinramharak** [comment]
Ill take a shot at that. I cloned the repo and look into the contribution guidelines.

**Comment by kevinramharak** [comment]
Running the tests locally does seem to fail:
```
 PASS  test/index.test.ts (5.257s)
 FAIL  test/fsbacked.test.ts (5.459s)
  ● can import files in the virtual fs

    expect(received).toEqual(expected) // deep equality

    - Expected  - 1
    + Received  + 3

    - Array []
    + Array [
    +   "Cannot find module './file-with-export' or its corresponding type declarations.",
    + ]

      56 |   errs.push(...env.languageService.getSyntacticDiagnostics(index))
      57 | 
    > 58 |   expect(errs.map(e => e.messageText)).toEqual([])
         |                                        ^
      59 | })
      60 | 

      at Object.<anonymous> (test/fsbacked.test.ts:58:40)
```

Is there a set in stone way of debugging tests? I think I can figure it out, but tsdx is still new to me.

**Comment by kevinramharak** [comment]
Well debugging is suprisingly easy. VSCode allows to attach a debugger to `yarn test`. The reason my test is failing is because the `fsMap` looks like:
```
0:(2) ['C:\\Users\\kevin\\Documents\\Projects\\TypeScript-Website\\fake\\file-with-export.ts', 'export const helloWorld = "Example string";']
1:(2) ['C:\\Users\\kevin\\Documents\\Projects\\TypeScript-Website\\fake\\index.ts', 'import {helloWorld} from "./file-with-export"; console.log(helloWorld)']
```
And it tries to fetch the file with the key: `C:/Users/kevin/Documents/Projects/TypeScript-Website/fake/index.ts`.

I'll open an issue for that, and try to find the original bug in WSL
