### ISSUE TITLE
V2 fails to load TypeScript 3.7 notes

### ISSUE THREAD

**Issue by gganley** [microsoft/TypeScript-Website#178]
White page when attempting to open https://www.typescriptlang.org/v2/docs/handbook/release-notes/typescript-3-7.html

```
Failed to load resource: the server responded with a status of 404 (Not Found)
/v2/manifest.webmanifest:1 Manifest: Line: 1, column: 1, Syntax error.
2react-dom.production.min.js:4684 DOMException: Failed to execute 'querySelector' on 'Document': '#37-breaking-changes' is not a valid selector.
    at https://www.typescriptlang.org/v2/component---src-templates-handbook-tsx-e1c9c5e86b6ba653deb4.js:1:7869
    at NodeList.forEach (<anonymous>)
    at t (https://www.typescriptlang.org/v2/component---src-templates-handbook-tsx-e1c9c5e86b6ba653deb4.js:1:7833)
    at https://www.typescriptlang.org/v2/component---src-templates-handbook-tsx-e1c9c5e86b6ba653deb4.js:1:8078
    at bo (https://www.typescriptlang.org/v2/commons-7fa04f7822f1d1db5170.js:1:149622)
    at Uu (https://www.typescriptlang.org/v2/commons-7fa04f7822f1d1db5170.js:1:174517)
    at t.unstable_runWithPriority (https://www.typescriptlang.org/v2/commons-7fa04f7822f1d1db5170.js:1:51142)
    at qa (https://www.typescriptlang.org/v2/commons-7fa04f7822f1d1db5170.js:1:117274)
    at Fu (https://www.typescriptlang.org/v2/commons-7fa04f7822f1d1db5170.js:1:174273)
    at https://www.typescriptlang.org/v2/commons-7fa04f7822f1d1db5170.js:1:174184
yo @ react-dom.production.min.js:4684
scheduler.production.min.js:104 Uncaught DOMException: Failed to execute 'querySelector' on 'Document': '#37-breaking-changes' is not a valid selector.
    at https://www.typescriptlang.org/v2/component---src-templates-handbook-tsx-e1c9c5e86b6ba653deb4.js:1:7869
    at NodeList.forEach (<anonymous>)
    at t (https://www.typescriptlang.org/v2/component---src-templates-handbook-tsx-e1c9c5e86b6ba653deb4.js:1:7833)
    at https://www.typescriptlang.org/v2/component---src-templates-handbook-tsx-e1c9c5e86b6ba653deb4.js:1:8078
    at bo (https://www.typescriptlang.org/v2/commons-7fa04f7822f1d1db5170.js:1:149622)
    at Uu (https://www.typescriptlang.org/v2/commons-7fa04f7822f1d1db5170.js:1:174517)
    at t.unstable_runWithPriority (https://www.typescriptlang.org/v2/commons-7fa04f7822f1d1db5170.js:1:51142)
    at qa (https://www.typescriptlang.org/v2/commons-7fa04f7822f1d1db5170.js:1:117274)
    at Fu (https://www.typescriptlang.org/v2/commons-7fa04f7822f1d1db5170.js:1:174273)
    at https://www.typescriptlang.org/v2/commons-7fa04f7822f1d1db5170.js:1:174184
docsearch.js:2 Uncaught Error: Error: No input element in the page matches .search input
    at Function.checkArguments (VM79 docsearch.js:2)
    at new DocSearch (VM79 docsearch.js:2)
    at Factory (VM79 docsearch.js:2)
    at HTMLScriptElement.e.onload (TopNav.tsx:27)
```

**Comment by orta** [comment]
Fixed with #245
