### ISSUE TITLE
`yarn start` fails

### ISSUE THREAD

**Issue by DanielRosenwasser** [microsoft/TypeScript-Website#1793]
I've tried this both on Windows

```
Microsoft Windows [Version 10.0.19042.928]
```

and in a Codespace

```
Distributor ID: Debian
Description:    Debian GNU/Linux 10 (buster)
Release:        10
Codename:       buster
```

```
> yarn start
[BUILD] Watchman:  spawn watchman ENOENT
[BUILD] Error while talking to watchman:  Error: spawn watchman ENOENT
[BUILD]     at Process.ChildProcess._handle.onexit (internal/child_process.js:268:19)
[BUILD]     at onErrorNT (internal/child_process.js:464:16)
[BUILD]     at processTicksAndRejections (internal/process/task_queues.js:80:21) {
[BUILD]   errno: -4058,
[BUILD]   code: 'ENOENT',
[BUILD]   syscall: 'spawn watchman',
[BUILD]   path: 'watchman',
[BUILD]   spawnargs: [ '--no-pretty', 'get-sockname' ]
[BUILD] }
[BUILD] node watcher.js exited with code 0
--> Sending SIGTERM to other processes..
[SITE] yarn workspace typescriptlang-org start exited with code 1

**Comment by orta** [comment]
I see, so no watchman set up

I think we can probably make the build watcher optional and give a message what you're _not_ getting by it not launching

**Comment by orta** [comment]
This is fixed 👍🏻  tested on my own code space
