### ISSUE TITLE
TypeScript 3.7 release notes page "crashes"?

### ISSUE THREAD

**Issue by DanielRosenwasser** [microsoft/TypeScript-Website#234]
https://www.typescriptlang.org/v2/docs/handbook/release-notes/typescript-3-7.html

doesn't load, and has the following errors in the console

```
react-dom.production.min.js:4684 DOMException: Failed to execute 'querySelector' on 'Document': '#37-breaking-changes' is not a valid selector.
    at https://www.typescriptlang.org/v2/component---src-templates-handbook-tsx-72eb9d854900b638a9ce.js:1:7878
    at NodeList.forEach (<anonymous>)
    at t (https://www.typescriptlang.org/v2/component---src-templates-handbook-tsx-72eb9d854900b638a9ce.js:1:7842)
    at https://www.typescriptlang.org/v2/component---src-templates-handbook-tsx-72eb9d854900b638a9ce.js:1:8087
    at bl (https://www.typescriptlang.org/v2/commons-e2735ad4f1e5959bb498.js:1:209347)
    at Du (https://www.typescriptlang.org/v2/commons-e2735ad4f1e5959bb498.js:1:234242)
    at t.unstable_runWithPriority (https://www.typescriptlang.org/v2/commons-e2735ad4f1e5959bb498.js:1:105026)
    at qa (https://www.typescriptlang.org/v2/commons-e2735ad4f1e5959bb498.js:1:176999)
    at Fu (https://www.typescriptlang.org/v2/commons-e2735ad4f1e5959bb498.js:1:233998)
    at https://www.typescriptlang.org/v2/commons-e2735ad4f1e5959bb498.js:1:233909
yl @ commons-e2735ad4f1e5959bb498.js:1


scheduler.production.min.js:104 Uncaught DOMException: Failed to execute 'querySelector' on 'Document': '#37-breaking-changes' is not a valid selector.
    at https://www.typescriptlang.org/v2/component---src-templates-handbook-tsx-72eb9d854900b638a9ce.js:1:7878
    at NodeList.forEach (<anonymous>)
    at t (https://www.typescriptlang.org/v2/component---src-templates-handbook-tsx-72eb9d854900b638a9ce.js:1:7842)
    at https://www.typescriptlang.org/v2/component---src-templates-handbook-tsx-72eb9d854900b638a9ce.js:1:8087
    at bl (https://www.typescriptlang.org/v2/commons-e2735ad4f1e5959bb498.js:1:209347)
    at Du (https://www.typescriptlang.org/v2/commons-e2735ad4f1e5959bb498.js:1:234242)
    at t.unstable_runWithPriority (https://www.typescriptlang.org/v2/commons-e2735ad4f1e5959bb498.js:1:105026)
    at qa (https://www.typescriptlang.org/v2/commons-e2735ad4f1e5959bb498.js:1:176999)
    at Fu (https://www.typescriptlang.org/v2/commons-e2735ad4f1e5959bb498.js:1:233998)
    at https://www.typescriptlang.org/v2/commons-e2735ad4f1e5959bb498.js:1:233909


Uncaught Error: Error: No input element in the page matches .search input
    at Function.checkArguments (docsearch.js:2)
    at new DocSearch (docsearch.js:2)
    at Factory (docsearch.js:2)
    at HTMLScriptElement.e.onload (TopNav.tsx:31)
```

**Comment by orta** [comment]
It looks like that's during the generation of the sidebar - wonder what's up there

**Comment by orta** [comment]
Fixed with #245

**Comment by ZuBB** [comment]
seems this just come back with new release/deploy

<img width="1440" alt="Screenshot 2020-08-06 at 19 05 41" src="https://user-images.githubusercontent.com/597016/89554735-ea998b00-d817-11ea-885c-6bc07f04574c.png">

**Comment by orta** [comment]
Yeah, this was a HTML comment which wasn't closed in the examples, fixed now

**Comment by ZuBB** [comment]
Thank you, @orta

**Comment by kevinramharak** [comment]
Seems to be happening again? @orta 
![image](https://user-images.githubusercontent.com/14903712/110704560-6c5df680-81f5-11eb-94ff-7fc2392029a2.png)
Not sure how these id's are generated, maybe use an escape sequence to represent numbers? https://stackoverflow.com/a/20306237
