### ISSUE TITLE
Docs: Cookies are now required

### ISSUE THREAD

**Issue by danielzgtg** [microsoft/TypeScript-Website#653]
**Page URL:** https://www.typescriptlang.org/

**Issue:** The page is blank

**Recommended Fix:** Add a try-catch around any `localStorage` access.

**Browser:** `Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/83.0.4103.61 Safari/537.36` with cookies disabled.

```
react-dom.production.min.js:4684 DOMException: Failed to read the 'localStorage' property from 'Window': Access is denied for this document.
    at https://www.typescriptlang.org/commons-6991d9c87f1dd7734339.js:1:99452
    at bl (https://www.typescriptlang.org/commons-6991d9c87f1dd7734339.js:1:241189)
    at Fu (https://www.typescriptlang.org/commons-6991d9c87f1dd7734339.js:1:266084)
    at t.unstable_runWithPriority (https://www.typescriptlang.org/commons-6991d9c87f1dd7734339.js:1:135483)
    at Ga (https://www.typescriptlang.org/commons-6991d9c87f1dd7734339.js:1:208841)
    at Du (https://www.typescriptlang.org/commons-6991d9c87f1dd7734339.js:1:265840)
    at https://www.typescriptlang.org/commons-6991d9c87f1dd7734339.js:1:265751
    at z (https://www.typescriptlang.org/commons-6991d9c87f1dd7734339.js:1:134865)
    at MessagePort.S.port1.onmessage (https://www.typescriptlang.org/commons-6991d9c87f1dd7734339.js:1:133609)
yl @ commons-6991d9c87f1dd7734339.js:1
Pl.i.componentDidCatch.n.callback @ commons-6991d9c87f1dd7734339.js:1
Si @ commons-6991d9c87f1dd7734339.js:1
wi @ commons-6991d9c87f1dd7734339.js:1
ju @ commons-6991d9c87f1dd7734339.js:1
t.unstable_runWithPriority @ commons-6991d9c87f1dd7734339.js:1
Ga @ commons-6991d9c87f1dd7734339.js:1
Mu @ commons-6991d9c87f1dd7734339.js:1
Tu @ commons-6991d9c87f1dd7734339.js:1
(anonymous) @ commons-6991d9c87f1dd7734339.js:1
t.unstable_runWithPriority @ commons-6991d9c87f1dd7734339.js:1
Ga @ commons-6991d9c87f1dd7734339.js:1
Za @ commons-6991d9c87f1dd7734339.js:1
Xa @ commons-6991d9c87f1dd7734339.js:1
Fu @ commons-6991d9c87f1dd7734339.js:1
t.unstable_runWithPriority @ commons-6991d9c87f1dd7734339.js:1
Ga @ commons-6991d9c87f1dd7734339.js:1
Du @ commons-6991d9c87f1dd7734339.js:1
(anonymous) @ commons-6991d9c87f1dd7734339.js:1
z @ commons-6991d9c87f1dd7734339.js:1
S.port1.onmessage @ commons-6991d9c87f1dd7734339.js:1
react-dom.production.min.js:4684 DOMException: Failed to read the 'localStorage' property from 'Window': Access is denied for this document.
    at https://www.typescriptlang.org/commons-6991d9c87f1dd7734339.js:1:99452
    at bl (https://www.typescriptlang.org/commons-6991d9c87f1dd7734339.js:1:241189)
    at Fu (https://www.typescriptlang.org/commons-6991d9c87f1dd7734339.js:1:266084)
    at t.unstable_runWithPriority (https://www.typescriptlang.org/commons-6991d9c87f1dd7734339.js:1:135483)
    at Ga (https://www.typescriptlang.org/commons-6991d9c87f1dd7734339.js:1:208841)
    at Du (https://www.typescriptlang.org/commons-6991d9c87f1dd7734339.js:1:265840)
    at https://www.typescriptlang.org/commons-6991d9c87f1dd7734339.js:1:265751
    at z (https://www.typescriptlang.org/commons-6991d9c87f1dd7734339.js:1:134865)
    at MessagePort.S.port1.onmessage (https://www.typescriptlang.org/commons-6991d9c87f1dd7734339.js:1:133609)
yl @ commons-6991d9c87f1dd7734339.js:1
Al.n.callback @ commons-6991d9c87f1dd7734339.js:1
Si @ commons-6991d9c87f1dd7734339.js:1
wi @ commons-6991d9c87f1dd7734339.js:1
ju @ commons-6991d9c87f1dd7734339.js:1
t.unstable_runWithPriority @ commons-6991d9c87f1dd7734339.js:1
Ga @ commons-6991d9c87f1dd7734339.js:1
Mu @ commons-6991d9c87f1dd7734339.js:1
Tu @ commons-6991d9c87f1dd7734339.js:1
(anonymous) @ commons-6991d9c87f1dd7734339.js:1
t.unstable_runWithPriority @ commons-6991d9c87f1dd7734339.js:1
Ga @ commons-6991d9c87f1dd7734339.js:1
Za @ commons-6991d9c87f1dd7734339.js:1
Xa @ commons-6991d9c87f1dd7734339.js:1
Fu @ commons-6991d9c87f1dd7734339.js:1
t.unstable_runWithPriority @ commons-6991d9c87f1dd7734339.js:1
Ga @ commons-6991d9c87f1dd7734339.js:1
Du @ commons-6991d9c87f1dd7734339.js:1
(anonymous) @ commons-6991d9c87f1dd7734339.js:1
z @ commons-6991d9c87f1dd7734339.js:1
S.port1.onmessage @ commons-6991d9c87f1dd7734339.js:1
scheduler.production.min.js:104 Uncaught DOMException: Failed to read the 'localStorage' property from 'Window': Access is denied for this document.
    at https://www.typescriptlang.org/commons-6991d9c87f1dd7734339.js:1:99452
    at bl (https://www.typescriptlang.org/commons-6991d9c87f1dd7734339.js:1:241189)
    at Fu (https://www.typescriptlang.org/commons-6991d9c87f1dd7734339.js:1:266084)
    at t.unstable_runWithPriority (https://www.typescriptlang.org/commons-6991d9c87f1dd7734339.js:1:135483)
    at Ga (https://www.typescriptlang.org/commons-6991d9c87f1dd7734339.js:1:208841)
    at Du (https://www.typescriptlang.org/commons-6991d9c87f1dd7734339.js:1:265840)
    at https://www.typescriptlang.org/commons-6991d9c87f1dd7734339.js:1:265751
    at z (https://www.typescriptlang.org/commons-6991d9c87f1dd7734339.js:1:134865)
    at MessagePort.S.port1.onmessage (https://www.typescriptlang.org/commons-6991d9c87f1dd7734339.js:1:133609)
S.port1.onmessage @ commons-6991d9c87f1dd7734339.js:1
docsearch.js:2 Uncaught Error: Error: No input element in the page matches .search input
    at Function.checkArguments (docsearch.js:2)
    at new DocSearch (docsearch.js:2)
    at Factory (docsearch.js:2)
    at HTMLScriptElement.e.onload (TopNav.tsx:34)
```

**Comment by orta** [comment]
Wow, it raises when you check if it exists (which is what causes this fail) - should be easy for the site but, I'll probably have to put a block on accessing the playground if you have this set.

**Comment by danielzgtg** [comment]
This bug is not happening to me anymore right now but it looks like the website was rolled back

**Comment by orta** [comment]
Yeah, we only deploy the new website over the weekends ATM
